spring:
  application:
    name: easy-rpc-spring-boot-starter-server

server:
  port: 8080

easy-rpc:
  connect-timeout: 4000
  server-port: 9998
  enable-server: true


eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://10.170.164.16:8082/eureka/